spring:
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://snuffleupagus.db.elephantsql.com:5432/mnjcmcnl"
    username: "mnjcmcnl"
    password: "DbKrZaNMTYzYD_aAozL0NQX3KnZunhpC"
    jta-managed: false
    dbcp2:
      initial-size: 1
      max-active: 2
      max-idle: 1
      min-idle: 1
